spring:
  application:
    name: paymentservice

  datasource:
    url: jdbc:postgresql://localhost:5432/payment_database
    username: sidharth
    password: postgres


  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true


server:
  port: 8083

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

stripe:
  secret-key: ${STRIPE_SECRET_KEY}